import { StyleSheet } from 'react-native';

const first = StyleSheet.create({
  container: {
    width: 375,
    height: 740,
    backgroundColor: '#ffffff',
    position: 'relative',
    overflow: 'hidden',
    marginTop: 0,
    marginRight: 'auto',
    marginBottom: 0,
    marginLeft: 'auto',
  },
  headerText: {
    height: 30,
    fontFamily: 'Inter',
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 25.2,
    color: '#000000',
    letterSpacing: 0.84,
    position: 'relative',
    textAlign: 'left',
    zIndex: 1,
    marginTop: 15,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 98,
  },
  firstImage: {
    width: 95.712,
    height: 120,
    position: 'relative',
    zIndex: 2,
    marginTop: 9,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 281.867,
  },
  welcomeText: {
    display: 'flex',
    width: 249,
    height: 149,
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    fontFamily: 'Inter',
    fontSize: 38,
    fontWeight: '600',
    lineHeight: 68.4,
    color: '#000000',
    letterSpacing: 2.28,
    position: 'absolute',
    top: 174,
    left: '50%',
    textAlign: 'left',
    overflow: 'hidden',
    transform: [{ translateX: -162.5 }],
  },
  robotImage: {
    width: 132,
    height: 170,
    position: 'absolute',
    top: 273,
    left: 222,
    zIndex: 4,
  },
  startImage: {
    width: 126,
    height: 122,
    position: 'absolute',
    top: 350,
    left: 221,
    zIndex: 9,
  },
  startText: {
    display: 'flex',
    height: 32,
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    fontFamily: 'Inter',
    fontSize: 17,
    fontWeight: '700',
    lineHeight: 30.6,
    color: '#000000',
    letterSpacing: 1.02,
    position: 'absolute',
    top: 45,
    left: '50%',
    textAlign: 'left',
    zIndex: 6,
    transform: [{ translateX: -27.5 }],
  },
  powerImage: {
    width: 120,
    height: 120,
    position: 'absolute',
    top: 620,
    left: 20,
    zIndex: 3,
  },
});

export default first;