import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    width: 375,
    height: 812,
    backgroundColor: '#ffffff',
    position: 'relative',
    overflow: 'hidden',
    marginTop: 0,
    marginRight: 'auto',
    marginBottom: 0,
    marginLeft: 'auto',
  },
  header: {
    width: 206,
    height: 36,
    position: 'relative',
    zIndex: 20,
    marginTop: 59,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 152,
  },
  headerText: {
    display: 'flex',
    width: 70,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
    fontFamily: 'Inter',
    fontSize: 24,
    fontWeight: '600',
    lineHeight: 36,
    color: '#000000',
    letterSpacing: -0.24,
    position: 'absolute',
    top: 0,
    left: '50%',
    textAlign: 'center',
    transform: [{ translateX: -103 }],
  },
  profileImage: {
    width: 24,
    height: 24,
    position: 'absolute',
    top: 12,
    right: 0,
    zIndex: 20,
  },
  newsSection: {
    display: 'flex',
    width: 169,
    gap: 4,
    alignItems: 'flex-start',
    flexWrap: 'nowrap',
    position: 'relative',
    zIndex: 23,
    marginTop: 27,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 11,
  },
  newsTitle: {
    height: 19,
    flexShrink: 0,
    flexBasis: 'auto',
    fontFamily: 'Inter',
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 19,
    color: '#000000',
    letterSpacing: -0.32,
    position: 'relative',
    textAlign: 'left',
    zIndex: 24,
  },
  newsSubtitle: {
    display: 'flex',
    width: 139,
    height: 20,
    justifyContent: 'flex-start',
    alignItems: 'center',
    flexShrink: 0,
    flexBasis: 'auto',
    fontFamily: 'Inter',
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 19.6,
    color: 'rgba(0, 0, 0, 0.5)',
    position: 'relative',
    textAlign: 'left',
    overflow: 'hidden',
    zIndex: 25,
  },
  backgroundImage: {
    width: 337,
    height: 183,
    backgroundColor: 'rgba(180, 219, 255, 0.2)',
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    borderBottomRightRadius: 8,
    borderBottomLeftRadius: 8,
    position: 'relative',
    overflow: 'hidden',
    zIndex: 21,
    marginTop: 20,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 19,
  },
  backgroundText: {
    display: 'flex',
    height: 12,
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    fontFamily: 'Inter',
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 12,
    color: '#ffffff',
    letterSpacing: -0.48,
    position: 'absolute',
    top: 10,
    left: 7,
    textAlign: 'left',
    zIndex: 22,
  },
  serviceSection: {
    display: 'flex',
    width: 169,
    gap: 4,
    alignItems: 'flex-start',
    flexWrap: 'nowrap',
    position: 'relative',
    zIndex: 17,
    marginTop: 31,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 11,
  },
  serviceTitle: {
    height: 19,
    flexShrink: 0,
    flexBasis: 'auto',
    fontFamily: 'Inter',
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 19,
    color: '#000000',
    letterSpacing: -0.32,
    position: 'relative',
    textAlign: 'left',
    zIndex: 18,
  },
  serviceSubtitle: {
    display: 'flex',
    width: 139,
    height: 20,
    justifyContent: 'flex-start',
    alignItems: 'center',
    flexShrink: 0,
    flexBasis: 'auto',
    fontFamily: 'Inter',
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 19.6,
    color: 'rgba(0, 0, 0, 0.5)',
    position: 'relative',
    textAlign: 'left',
    overflow: 'hidden',
    zIndex: 19,
  },
  iconRow: {
    display: 'flex',
    width: 268,
    height: 128,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    position: 'relative',
    zIndex: 5,
    marginTop: 15,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 53,
  },
  iconContainer: {
    display: 'flex',
    width: 100,
    gap: 8,
    alignItems: 'flex-start',
    flexShrink: 0,
    flexWrap: 'nowrap',
    position: 'relative',
    zIndex: 1,
  },
  iconImage: {
    width: 100,
    height: 100,
    flexShrink: 0,
    backgroundColor: 'rgba(231, 243, 255, 0.2)',
    borderTopLeftRadius: 48,
    borderTopRightRadius: 48,
    borderBottomRightRadius: 48,
    borderBottomLeftRadius: 48,
    position: 'relative',
    overflow: 'hidden',
    zIndex: 2,
  },
  iconTextContainer: {
    display: 'flex',
    width: 100,
    alignItems: 'flex-start',
    flexShrink: 0,
    flexWrap: 'nowrap',
    position: 'relative',
    zIndex: 3,
  },
  iconText: {
    display: 'flex',
    width: 100,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
    flexShrink: 0,
    flexBasis: 'auto',
    fontFamily: 'Inter',
    fontSize: 14,
    fontWeight: '500',
    lineHeight: 19.6,
    color: '#000000',
    position: 'relative',
    textAlign: 'center',
    overflow: 'hidden',
    zIndex: 4,
  },
});

export default styles;